name: ds_build-and-publish
run-name: Publish Discovery Server image to registry.gitlab.com
on: [workflow_dispatch] # manual
jobs:
  build-publish:
    name: Build and publish to registry.gitlab.com/pacebuddies private registry
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Discovery Server repo
        uses: actions/checkout@master
        with:
          repository: pacebuddies/discovery-server
          ref: master
          token: ${{ secrets.PAT }}

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: ./mvnw --quiet clean package -DskipTests

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: szyorz/pacebuddies/discovery_server

      - name: Publish to registry.gitlab.com
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: registry.gitlab.com/pacebuddies/discovery_server:latest


