name: frontend_build-and-publish
run-name: Publish Frontend image to registry.gitlab.com
on: [workflow_dispatch] # manual
jobs:
  build-publish:
    name: Build and publish to registry.gitlab.com/pacebuddies private registry
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Frontend repo
        uses: actions/checkout@master
        with:
          repository: pacebuddies/Frontend
          ref: main
          token: ${{ secrets.PAT }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: szyorz/pacebuddies/frontend

      - name: Publish to registry.gitlab.com
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: registry.gitlab.com/pacebuddies/frontend:latest


